CONFIG_ZMK_POINTING=y

# Incrementar la potencia de transmisión de las antenas Bluetooth al máximo (+8 dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Estabilizar la conexión entre ambas mitades del teclado
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
